"""Authored operational block inputs, fixed before an execution owner starts.

Each block keeps its host and store across twelve scheduled cases; external
resources are distinct so case order cannot change the injected faults or
expected remaining state. Definitions reuse the hand-written workflow, while
expected outcomes below are independent literals, never generated by fsm.
"""
import json
from pathlib import Path

from .executor_scenarios import workflow_table
from .soak import CASES


def resource_names():
    return tuple('soak-' + case for case in CASES) + ('soak-contention-right',)


def block_inputs(kind, resource_root, handler, workflow):
    """Compile no machine and run no operation; return the fixed input catalog."""
    if kind not in ('process', 'mcp'):
        raise ValueError('operational fixtures require an explicit handler kind')
    resource_root, handler = Path(resource_root), Path(handler)
    original = json.loads(Path(workflow).read_text())
    machines, handlers, manuals = {}, [], []
    for case in CASES:
        machine, table = _case_inputs(original, case, kind, resource_root, handler)
        machines[case] = machine
        handlers.extend(table['handlers'])
        manuals.extend(table['manual_effects'])
    # Both contention instances use the same real handler pool with one slot;
    # distinct external resources permit any legal interleaving of operations.
    right = json.loads(json.dumps(machines['contention']))
    right['name'] += '_right'
    for state in right['states']:
        for emission in state.get('entry', {}).get('emit', []):
            if 'resource' in emission['args']:
                emission['args']['resource'] = json.dumps('soak-contention-right')
    machines['contention-right'] = right
    table = dict(format='fsm.handlers/1', max_inflight=1, max_inflight_per_instance=1,
                 handlers=handlers, manual_effects=manuals)
    if len(json.dumps(table, sort_keys=True, separators=(',', ':')).encode()) > 65_536:
        raise ValueError('operational block exceeds the protected catalog byte bound')
    return dict(machines=machines, table=table, resources=resource_names())


def _case_inputs(original, case, kind, resource_root, handler):
    specification = json.loads(json.dumps(original))
    prefix = 'soak_' + case + '_'
    specification['name'] = 'soak_' + case
    for effect in specification['effects']:
        effect['name'] = prefix + effect['name']
    for state in specification['states']:
        for emission in state.get('entry', {}).get('emit', []):
            emission['effect'] = prefix + emission['effect']
            if 'resource' in emission['args']:
                emission['args']['resource'] = json.dumps('soak-' + case)
    table = workflow_table(resource_root, handler, kind=kind,
                           outcome='partial-work' if case == 'compensate' else 'success')
    table['manual_effects'] = [prefix + name for name in table['manual_effects']]
    for entry in table['handlers']:
        entry['effect'] = prefix + entry['effect']
        command = entry['argv']
        command[command.index('--run') + 1] = entry['effect']
        command.extend(['--observe-timing'])
        if entry['effect'].endswith('validate_resource'):
            command.extend(['--release', str((resource_root / ('release-' + case)).resolve()),
                            '--wait-seconds', '60'])
            if case == 'retry':
                command.append('--fail-first')
                entry['retry'] = dict(attempts=2, backoff_ms=25,
                                     on=['nonzero_exit' if kind == 'process' else 'mcp_error'])
            if case == 'deadline':
                entry['timeout_ms'] = 2000
                command.append('--descendant')
            if case == 'noise':
                command.extend(['--noise-bytes', '131072'])
    return specification, table


def completed_ledger(case, resource=None):
    """Literal physical expectations for cases with an ordinary completed path."""
    if case not in set(CASES) - {'manual', 'deadline', 'cancel'}:
        raise ValueError('this case needs manual or interrupted-domain evidence')
    attempts = [('validate', 0), ('suspend', 0), ('process', 0), ('restore', 0)]
    mutations = ['suspend', 'process:0', 'process:1', 'restore']
    state = dict(suspended=False, items=[0, 1])
    if case == 'retry':
        attempts.insert(0, ('validate', 3))
    if case == 'compensate':
        attempts[2] = ('process', 3)
        mutations = ['suspend', 'process:0', 'restore']
        state['items'] = [0]
    expected_resource = 'soak-' + case
    if resource is not None:
        if case != 'contention' or resource != 'soak-contention-right':
            raise ValueError('only the authored second contention resource is permitted')
        expected_resource = resource
    return dict(resource=expected_resource, attempts=attempts, mutations=mutations, state=state)
