[package]
name = "fsm-cli"
edition.workspace = true
rust-version.workspace = true
version.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "fsm"
path = "src/main.rs"

[dependencies]
fsm-core = { path = "../fsm-core" }
fsm-store = { path = "../fsm-store" }

[lints]
workspace = true
