pub(super) enum Host {
    Primitive,
    Shared,
    Fresh,
    FreshMcp,
    Cold,
    ColdMcp,
    ColdConflict,
    ColdConflictMcp,
    ColdRejected,
    ColdRejectedMcp,
    Admission,
    AdmissionMcp,
    AdmissionCancellation,
    AdmissionMcpCancellation,
    AdmissionCompetition,
    AdmissionMcpCompetition,
}
